#!/usr/bin/env python
# -*- coding: utf-8 -*- #
"""Docstring."""
from __future__ import unicode_literals

from hashlib import md5

AUTHOR = 'Kalman Olah'
SITENAME = 'Rants of a Troubled Consultant'
SITEURL = 'http://localhost:8000'

PATH = 'content'

TIMEZONE = 'Europe/Brussels'

DEFAULT_LANG = 'en'

# Post generation
DEFAULT_PAGINATION = 10
DEFAULT_CATEGORY = 'Uncategorized'

# Author generation
# AUTHOR_URL = None
# AUTHOR_SAVE_AS = ''
# AUTHORS_URL = None
# AUTHORS_SAVE_AS = ''

# Feed generation
FEED_DOMAIN = SITEURL
FEED_ALL_ATOM = None
CATEGORY_FEED_ATOM = None
TRANSLATION_FEED_ATOM = None
AUTHOR_FEED_ATOM = None

FEED_RSS = 'blog/feed'
FEED_ALL_RSS = 'feeds/all.rss'
AUTHOR_FEED_RSS = 'feeds/%s.rss'
CATEGORY_FEED_RSS = 'feeds/%s.rss'
FEED_MAX_ITEMS = 10

# Links
LINKS = (('Source', 'https://github.com/kalmanolah/kalmanolah.github.io/tree/source'),)

# Social widget
SOCIAL = (('github', 'https://github.com/kalmanolah'),
          ('linkedin', 'https://linkedin.com/in/KalmanOlah'),
          ('twitter', 'https://twitter.com/KalmanOlah'),
          ('envelope-o', '/assets/misc/pubkey.asc'),
          ('google', 'https://plus.google.com/+KalmanOlah1'),
          # ('keybase', 'https://keybase.io/kalman'),
          ('rss', '/feeds/all.rss'))

# Assets
STATIC_PATHS = ['assets']
EXTRA_PATH_METADATA = {
    'assets/robots.txt': {'path': 'robots.txt'},
    'assets/apple-touch-icon.png': {'path': 'apple-touch-icon.png'},
    'assets/favicon.ico': {'path': 'favicon.ico'},
}

# Uncomment following line if you want document-relative URLs when developing
# RELATIVE_URLS = True

# Theme && Theme-specific
THEME = './modules/pelican-flex'
FAVICON = SITEURL + '/favicon.ico'

# Basic site info
SITETITLE = SITENAME
SITESUBTITLE = 'Textual output generated by Kalman Olah: a pretty cool tech person who likes automation, game development, hardware, \
privacy and lazing about.'
SITEDESCRIPTION = SITESUBTITLE
COPYRIGHT_YEAR = 2015
SITELOGO = SITEURL + '/assets/img/stock_photo_of_some_asshole.png'

# Annoying integrations
GOOGLE_ANALYTICS = 'UA-38768307-1'
DISQUS_SITENAME = 'kalmanolah'

# SEO
OG_LOCALE = '%s_BE' % DEFAULT_LANG
ROBOTS = 'index, follow'

# Menu
MAIN_MENU = True
MENUITEMS = (('Archives', '/archives.html'),
             ('Categories', '/categories.html'),
             ('Tags', '/tags.html'),)

# Plugins
PLUGIN_PATHS = ['./modules/pelican-plugins']
PLUGINS = ['optimize_images', 'sitemap', 'gzip_cache']

# Plugin config
GZIP_CACHE_OVERWRITE = False
SITEMAP = {
    'format': 'xml',
    'priorities': {
        'articles': 0.5,
        'indexes': 0.5,
        'pages': 0.5
    },
    'changefreqs': {
        'articles': 'monthly',
        'indexes': 'daily',
        'pages': 'monthly'
    }
}
